dist: trusty

language: python
matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial          # required for Python >= 3.7
    - python: 3.8
      env: TOXENV=py38
      dist: xenial          # required for Python >= 3.7

addons:
  apt:
    packages:
      - srecord

before_install:
  # asxxxx
  - wget -q -U travis http://6502.org/tools/asm/asxv5p31.zip
  - unzip -q asxv5p31.zip
  - make -C asxv5pxx/asxmak/linux/build all
  - export PATH=$PATH:$PWD/asxv5pxx/asxmak/linux/build

install:
  - travis_retry pip install tox

script:
  - travis_retry tox
