name: Run all tests

on: [push, pull_request]

env:
  PIP: "env PIP_DISABLE_PIP_VERSION_CHECK=1
            PYTHONWARNINGS=ignore:DEPRECATION
            pip --no-cache-dir"

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install asxxxx
      run: |
        wget --no-verbose https://github.com/6502org/6502.org/raw/74f5d0c0f9b73d5e353bde7b3b25ea7f43b527a1/public/tools/asm/asxs5p50.zip
        unzip -q asxs5p50.zip
        make -C asxv5pxx/asxmak/linux/build all
        echo "$PWD/asxv5pxx/asxmak/linux/build" >> $GITHUB_PATH

    - name: Install srecord
      run: |
        sudo apt-get update
        sudo apt-get install -y srecord

    - name: Show Python version
      run: python -V

    - name: Assemble debugger firmware
      run: make -C k0emu/debugger/firmware

    - name: Install dependencies
      run: $PIP install k0dasm

    - name: Run the tests
      run: python -m unittest discover -s k0emu/tests
